### ISSUE TITLE
Add $MNTPATH to RSYNC 

### ISSUE THREAD

**Issue by tddrane** [seamusdemora/RonR-RPi-image-utils#2]
If, like I, you get the message "No more room on device" when creating or updating and image, you probably need to move the TMP directory to another device. The script sets the variable MNTPATH which can be altered to do this however, RSYNC uses the system /TMP by default. 
Add the following to the RSYNC command line at line number 99

--temp-dir="$MNTPATH"
In my changed script the line starts:
rsync -aDH --temp-dir="$MNTPATH" --partial ........etc.

**Comment by seamusdemora** [comment]
Thanks for the issue notification. I've never seen this issue myself, but your change is *probably* a good one. 

Nevertheless, as I'm neither the author, not the maintainer of `image-utils`, I'm not going to take any action on this (other than note it, and mark it closed) - IAW the README.md file. I'd suggest that you post this to [Ron-R's image-utils post in the RPi forum here](https://forums.raspberrypi.com/viewtopic.php?t=247568).
