### ISSUE TITLE
Unsupported partition table type:

### ISSUE THREAD

**Issue by Stonk8** [seamusdemora/RonR-RPi-image-utils#7]
Tried to run image-utils on a Rasperry PI clone (Bigtreetech Pi v1.2) of my 3D printer. Got this message:
"Unsupported partition table type:"
Note that it is empty after it.

What can I do?
Thanks

**Comment by seamusdemora** [comment]
@Stonk8 asked, "What can I do?"

First thing would be to read the 1st paragraph of the README where it says: 

>Please take up any issues or questions in the [Image File Utilities](https://forums.raspberrypi.com/viewtopic.php?t=332000) thread of the Raspberry Pi Forums site. IOW: This is a file repository only; no support is available here.
