### ISSUE TITLE
Not working with samba share mount

### ISSUE THREAD

**Issue by DrStS** [seamusdemora/RonR-RPi-image-utils#8]
Hi,
I am trying to use the script with a samba share mount. The samba share mount seems to work fine when I operate on it with the pi user. 
Yet when I run the script is produces the following error message:

`Create /mnt/fritz/test.img (y/n)? y
sfdisk: cannot open /mnt/fritz/test.img: Invalid argument
sfdisk: cannot open /mnt/fritz/test.img: Invalid argument
losetup: /mnt/fritz/test.img: Warning: file is smaller than 512 bytes; the loop device may be useless or invisible for system tools.
Unable to create image BOOT filesystem`

The samba share is mounted with the following command: 

`sudo mount -t cifs //fritz.nas/FRITZ.NAS/Raspi_Back /mnt/fritz -o rw,noserverino,username=myuser,password=xxx,workgroup=WORKGROUP,uid=pi,gid=pi,noatime`

**Comment by leonundjulie** [comment]
Hi. I have the same problem. Were you able to solve the issue? Regards from Andreas

**Comment by seamusdemora** [comment]
Please follow the advice in the README, and [take your questions to the RPi forum](https://forums.raspberrypi.com/viewtopic.php?t=332000)
