### ISSUE TITLE
how to use NAS based on fritz.box

### ISSUE THREAD

**Issue by leonundjulie** [seamusdemora/RonR-RPi-image-utils#9]
I did as required. I mounted to my PI4 with a 120GB SSD (I lost already 2 SD Cards and learned from my mistakes; so I have it on a SSD now) a NAS (Fritz.Box with an attached 120GB SSD, ext4 formated) … I can read, write and delete files on the mounted ssd. So far so good. But starting the RonR and following happens:

![IMG_0990](https://github.com/user-attachments/assets/0dc9d9be-da3b-4afc-ac5d-65f36cf36ec2)
Image file to create? /mnt/nasbckp/nasbackup/test.img

Initial image file ROOT filesystem size (MB) [14606]? 15000

Added space for incremental updates after shrinking (MB) [0]? 5000

Create /mnt/nasbckp/nasbackup/test.img (y/n)? y sfdisk: cannot open /mnt/nasbckp/nasbackup/test.img: Das Argument ist ungültig sfdisk: cannot open /mnt/nasbckp/nasbackup/test.img: Das Argument ist ungültig losetup: /mnt/nasbckp/nasbackup/test.img: Warning: file is smaller than 512 bytes; the loop device may be useless or invisible for system tools.

Unable to create image BOOT filesystem

What is the reason? What is the mistake

**Comment by seamusdemora** [comment]
Please follow the advice in the README, and [take your questions to the RPi forum](https://forums.raspberrypi.com/viewtopic.php?t=332000)
